EXEC_PATH = "../scripts/platform.sh"

deploy:
	@$(EXEC_PATH) deploy

validate:
	@$(EXEC_PATH) validate

bootstrap:
	@$(EXEC_PATH) bootstrap all

bootstrap-identity:
	@$(EXEC_PATH) bootstrap identity

bootstrap-autoscaler:
	@$(EXEC_PATH) bootstrap autoscaler

delete:
	@$(EXEC_PATH) delete

purge:
	@$(EXEC_PATH) purge