EXEC_PATH = "../../eng/scripts/images.sh"

build:
	@$(EXEC_PATH) build all

build-linux:
	@$(EXEC_PATH) build linux

build-windows:
	@$(EXEC_PATH) build windows

push:
	@$(EXEC_PATH) push all

push-linux:
	@$(EXEC_PATH) push linux

push-windows:
	@$(EXEC_PATH) push windows
