---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: functions
  namespace: functions
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: functions
subjects:
  - kind: ServiceAccount
    name: functions
    namespace: functions
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
