EXEC_PATH = "../../eng/scripts/runtime.sh"

login:
	@$(EXEC_PATH) login

build:
	@$(EXEC_PATH) build

generate:
	@$(EXEC_PATH) generate

push:
	@$(EXEC_PATH) push

clean:
	@$(EXEC_PATH) clean

run:
	@$(EXEC_PATH) run

deploy:
	@$(EXEC_PATH) deploy

delete:
	@$(EXEC_PATH) delete
